// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: plat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取客户标志的请求参数
type GetPlatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 每个接口都需要的校验参数
	// 租户ID
	Ti string `protobuf:"bytes,1,opt,name=ti,proto3" json:"ti,omitempty"`
	// 客户端ID
	Ci string `protobuf:"bytes,2,opt,name=ci,proto3" json:"ci,omitempty"`
	// 密码
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// 时间戳
	T string `protobuf:"bytes,4,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *GetPlatRequest) Reset() {
	*x = GetPlatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatRequest) ProtoMessage() {}

func (x *GetPlatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatRequest.ProtoReflect.Descriptor instead.
func (*GetPlatRequest) Descriptor() ([]byte, []int) {
	return file_plat_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlatRequest) GetTi() string {
	if x != nil {
		return x.Ti
	}
	return ""
}

func (x *GetPlatRequest) GetCi() string {
	if x != nil {
		return x.Ci
	}
	return ""
}

func (x *GetPlatRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetPlatRequest) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

// 返回的数据结构响应参数
type IpAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数据端口
	Dport string `protobuf:"bytes,1,opt,name=dport,proto3" json:"dport,omitempty"`
	// 文件端口
	Fport string `protobuf:"bytes,2,opt,name=fport,proto3" json:"fport,omitempty"`
	// ip或者域名
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// 是否本地化部署
	Islocal int32 `protobuf:"varint,4,opt,name=islocal,proto3" json:"islocal,omitempty"`
	// 是否OSS保存文件
	Isoss int32 `protobuf:"varint,5,opt,name=isoss,proto3" json:"isoss,omitempty"`
}

func (x *IpAddr) Reset() {
	*x = IpAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddr) ProtoMessage() {}

func (x *IpAddr) ProtoReflect() protoreflect.Message {
	mi := &file_plat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddr.ProtoReflect.Descriptor instead.
func (*IpAddr) Descriptor() ([]byte, []int) {
	return file_plat_proto_rawDescGZIP(), []int{1}
}

func (x *IpAddr) GetDport() string {
	if x != nil {
		return x.Dport
	}
	return ""
}

func (x *IpAddr) GetFport() string {
	if x != nil {
		return x.Fport
	}
	return ""
}

func (x *IpAddr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpAddr) GetIslocal() int32 {
	if x != nil {
		return x.Islocal
	}
	return 0
}

func (x *IpAddr) GetIsoss() int32 {
	if x != nil {
		return x.Isoss
	}
	return 0
}

// 获取平台服务器的ip或者域名的响应参数
type GetServerIpReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 错误码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// ip域名参数
	Ipaddr *IpAddr `protobuf:"bytes,2,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
}

func (x *GetServerIpReply) Reset() {
	*x = GetServerIpReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerIpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerIpReply) ProtoMessage() {}

func (x *GetServerIpReply) ProtoReflect() protoreflect.Message {
	mi := &file_plat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerIpReply.ProtoReflect.Descriptor instead.
func (*GetServerIpReply) Descriptor() ([]byte, []int) {
	return file_plat_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerIpReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetServerIpReply) GetIpaddr() *IpAddr {
	if x != nil {
		return x.Ipaddr
	}
	return nil
}

var File_plat_proto protoreflect.FileDescriptor

var file_plat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x69, 0x12, 0x0e,
	0x0a, 0x02, 0x63, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x69, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67,
	0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x22, 0x74,
	0x0a, 0x06, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x73, 0x6f, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x73, 0x6f, 0x73, 0x73, 0x22, 0x47, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x06,
	0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x49,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x52, 0x06, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plat_proto_rawDescOnce sync.Once
	file_plat_proto_rawDescData = file_plat_proto_rawDesc
)

func file_plat_proto_rawDescGZIP() []byte {
	file_plat_proto_rawDescOnce.Do(func() {
		file_plat_proto_rawDescData = protoimpl.X.CompressGZIP(file_plat_proto_rawDescData)
	})
	return file_plat_proto_rawDescData
}

var file_plat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plat_proto_goTypes = []interface{}{
	(*GetPlatRequest)(nil),   // 0: GetPlatRequest
	(*IpAddr)(nil),           // 1: IpAddr
	(*GetServerIpReply)(nil), // 2: GetServerIpReply
}
var file_plat_proto_depIdxs = []int32{
	1, // 0: GetServerIpReply.ipaddr:type_name -> IpAddr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plat_proto_init() }
func file_plat_proto_init() {
	if File_plat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerIpReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plat_proto_goTypes,
		DependencyIndexes: file_plat_proto_depIdxs,
		MessageInfos:      file_plat_proto_msgTypes,
	}.Build()
	File_plat_proto = out.File
	file_plat_proto_rawDesc = nil
	file_plat_proto_goTypes = nil
	file_plat_proto_depIdxs = nil
}
